// app/layout.js
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import { ThemeProvider } from '../app/components/Providers';
import Tabs from './components/Tabs';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Movie App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
      <ThemeProvider>
        <div className="flex min-h-screen flex-col">
          <Header />
          <Tabs />
          <main>
            {children}
          </main>
        </div>
      </ThemeProvider>
      </body>
      </html>
  );
}